#
# Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_PINCTRL) 		+= core.o pinconf.o pinmux.o
obj-$(CONFIG_PINCTRL_CX800) += pinctrl-cx.o
