#ifndef S5PC110_H_
#define S5PC110_H_

//typedef volatile unsigned long 	vu_long;

#define __REG(x)	(*(vu_long *)(x))


/* - gpio controller reg config */
#define ELFIN_GPIO_BASE			0xE0200000

#define GPG0CON_OFFSET 			0x1A0 
#define GPG0DAT_OFFSET 			0x1A4 
#define GPG0PUD_OFFSET 			0x1A8 
#define GPG0DRV_SR_OFFSET 		0x1AC 
#define GPG0CONPDN_OFFSET 		0x1B0 
#define GPG0PUDPDN_OFFSET 		0x1B4 

#define GPG1CON_OFFSET 			0x1C0 
#define GPG1DAT_OFFSET 			0x1C4 
#define GPG1PUD_OFFSET 			0x1C8 
#define GPG1DRV_SR_OFFSET 		0x1CC 
#define GPG1CONPDN_OFFSET 		0x1D0 
#define GPG1PUDPDN_OFFSET 		0x1D4 

#define GPG2CON_OFFSET 			0x1E0 
#define GPG2DAT_OFFSET 			0x1E4 
#define GPG2PUD_OFFSET 			0x1E8 
#define GPG2DRV_SR_OFFSET 		0x1EC 
#define GPG2CONPDN_OFFSET 		0x1F0 
#define GPG2PUDPDN_OFFSET 		0x1F4 

#define GPG3CON_OFFSET 			0x200 
#define GPG3DAT_OFFSET 			0x204 
#define GPG3PUD_OFFSET 			0x208 
#define GPG3DRV_SR_OFFSET 		0x20C 
#define GPG3CONPDN_OFFSET 		0x210 
#define GPG3PUDPDN_OFFSET 		0x214

#define GPA0CON				(ELFIN_GPIO_BASE + GPA0CON_OFFSET)	 
#define GPA0DAT				(ELFIN_GPIO_BASE + GPA0DAT_OFFSET)		 
#define GPA0PUD				(ELFIN_GPIO_BASE + GPA0PUD_OFFSET)		 
#define GPA0DRV				(ELFIN_GPIO_BASE + GPA0DRV_SR_OFFSET)
#define GPA0CONPDN			(ELFIN_GPIO_BASE + GPA0CONPDN_OFFSET)	 
#define GPA0PUDPDN			(ELFIN_GPIO_BASE + GPA0PUDPDN_OFFSET)	 
#define GPA1CON				(ELFIN_GPIO_BASE + GPA1CON_OFFSET) 
#define GPA1DAT				(ELFIN_GPIO_BASE + GPA1DAT_OFFSET) 		 
#define GPA1PUD				(ELFIN_GPIO_BASE + GPA1PUD_OFFSET) 		 
#define GPA1DRV				(ELFIN_GPIO_BASE + GPA1DRV_SR_OFFSET) 	 
#define GPA1CONPDN			(ELFIN_GPIO_BASE + GPA1CONPDN_OFFSET) 	 
#define GPA1PUDPDN			(ELFIN_GPIO_BASE + GPA1PUDPDN_OFFSET) 	 
#define GPBCON				(ELFIN_GPIO_BASE + GPBCON_OFFSET) 
#define GPBDAT				(ELFIN_GPIO_BASE + GPBDAT_OFFSET)			 
#define GPBPUD				(ELFIN_GPIO_BASE + GPBPUD_OFFSET)			 
#define GPBDRV_SR			(ELFIN_GPIO_BASE + GPBDRV_SR_OFFSET)
#define GPBCONPDN			(ELFIN_GPIO_BASE + GPBCONPDN_OFFSET)	 
#define GPBPUDPDN			(ELFIN_GPIO_BASE + GPBPUDPDN_OFFSET)	 
#define GPC0CON				(ELFIN_GPIO_BASE + GPC0CON_OFFSET)	 
#define GPC0DAT				(ELFIN_GPIO_BASE + GPC0DAT_OFFSET)		 
#define GPC0PUD				(ELFIN_GPIO_BASE + GPC0PUD_OFFSET)		 
#define GPC0DRV				(ELFIN_GPIO_BASE + GPC0DRV_SR_OFFSET)
#define GPC0CONPDN			(ELFIN_GPIO_BASE + GPC0CONPDN_OFFSET)	 
#define GPC0PUDPDN			(ELFIN_GPIO_BASE + GPC0PUDPDN_OFFSET)	 
#define GPC1CON				(ELFIN_GPIO_BASE + GPC1CON_OFFSET) 
#define GPC1DAT				(ELFIN_GPIO_BASE + GPC1DAT_OFFSET)		 
#define GPC1PUD				(ELFIN_GPIO_BASE + GPC1PUD_OFFSET)		 
#define GPC1DRV				(ELFIN_GPIO_BASE + GPC1DRV_SR_OFFSET)
#define GPC1CONPDN			(ELFIN_GPIO_BASE + GPC1CONPDN_OFFSET)	 
#define GPC1PUDPDN			(ELFIN_GPIO_BASE + GPC1PUDPDN_OFFSET)	 
#define GPD0CON				(ELFIN_GPIO_BASE + GPD0CON_OFFSET) 
#define GPD0DAT				(ELFIN_GPIO_BASE + GPD0DAT_OFFSET)		 
#define GPD0PUD				(ELFIN_GPIO_BASE + GPD0PUD_OFFSET)		 
#define GPD0DRV				(ELFIN_GPIO_BASE + GPD0DRV_SR_OFFSET)
#define GPD0CONPDN			(ELFIN_GPIO_BASE + GPD0CONPDN_OFFSET)	 
#define GPD0PUDPDN			(ELFIN_GPIO_BASE + GPD0PUDPDN_OFFSET)	 
#define GPD1CON				(ELFIN_GPIO_BASE + GPD1CON_OFFSET) 
#define GPD1DAT				(ELFIN_GPIO_BASE + GPD1DAT_OFFSET)		 
#define GPD1PUD				(ELFIN_GPIO_BASE + GPD1PUD_OFFSET)		 
#define GPD1DRV				(ELFIN_GPIO_BASE + GPD1DRV_SR_OFFSET)
#define GPD1CONPDN			(ELFIN_GPIO_BASE + GPD1CONPDN_OFFSET)	 
#define GPD1PUDPDN			(ELFIN_GPIO_BASE + GPD1PUDPDN_OFFSET)	 
#define GPE0CON				(ELFIN_GPIO_BASE + GPE0CON_OFFSET) 
#define GPE0DAT				(ELFIN_GPIO_BASE + GPE0DAT_OFFSET)		 
#define GPE0PUD				(ELFIN_GPIO_BASE + GPE0PUD_OFFSET)		 
#define GPE0DRV				(ELFIN_GPIO_BASE + GPE0DRV_SR_OFFSET)
#define GPE0CONPDN			(ELFIN_GPIO_BASE + GPE0CONPDN_OFFSET)
#define GPE0PUDPDN			(ELFIN_GPIO_BASE + GPE0PUDPDN_OFFSET)	 
#define GPE1CON				(ELFIN_GPIO_BASE + GPE1CON_OFFSET) 
#define GPE1DAT				(ELFIN_GPIO_BASE + GPE1DAT_OFFSET)		 
#define GPE1PUD				(ELFIN_GPIO_BASE + GPE1PUD_OFFSET)		 
#define GPE1DRV				(ELFIN_GPIO_BASE + GPE1DRV_SR_OFFSET)
#define GPE1CONPDN			(ELFIN_GPIO_BASE + GPE1CONPDN_OFFSET)	 
#define GPE1PUDPDN			(ELFIN_GPIO_BASE + GPE1PUDPDN_OFFSET)	 
#define GPF0CON				(ELFIN_GPIO_BASE + GPF0CON_OFFSET) 
#define GPF0DAT				(ELFIN_GPIO_BASE + GPF0DAT_OFFSET)		 
#define GPF0PUD				(ELFIN_GPIO_BASE + GPF0PUD_OFFSET)		 
#define GPF0DRV				(ELFIN_GPIO_BASE + GPF0DRV_SR_OFFSET)
#define GPF0CONPDN			(ELFIN_GPIO_BASE + GPF0CONPDN_OFFSET)	 
#define GPF0PUDPDN			(ELFIN_GPIO_BASE + GPF0PUDPDN_OFFSET)	 
#define GPF1CON				(ELFIN_GPIO_BASE + GPF1CON_OFFSET) 
#define GPF1DAT				(ELFIN_GPIO_BASE + GPF1DAT_OFFSET)		 
#define GPF1PUD				(ELFIN_GPIO_BASE + GPF1PUD_OFFSET)		 
#define GPF1DRV				(ELFIN_GPIO_BASE + GPF1DRV_SR_OFFSET)
#define GPF1CONPDN			(ELFIN_GPIO_BASE + GPF1CONPDN_OFFSET)	 
#define GPF1PUDPDN			(ELFIN_GPIO_BASE + GPF1PUDPDN_OFFSET)	 
#define GPF2CON				(ELFIN_GPIO_BASE + GPF2CON_OFFSET) 
#define GPF2DAT				(ELFIN_GPIO_BASE + GPF2DAT_OFFSET)		 
#define GPF2PUD				(ELFIN_GPIO_BASE + GPF2PUD_OFFSET)		 
#define GPF2DRV				(ELFIN_GPIO_BASE + GPF2DRV_SR_OFFSET)	 
#define GPF2CONPDN			(ELFIN_GPIO_BASE + GPF2CONPDN_OFFSET)	 
#define GPF2PUDPDN			(ELFIN_GPIO_BASE + GPF2PUDPDN_OFFSET)	 
#define GPF3CON				(ELFIN_GPIO_BASE + GPF3CON_OFFSET) 
#define GPF3DAT				(ELFIN_GPIO_BASE + GPF3DAT_OFFSET)		 
#define GPF3PUD				(ELFIN_GPIO_BASE + GPF3PUD_OFFSET)		 
#define GPF3DRV				(ELFIN_GPIO_BASE + GPF3DRV_SR_OFFSET)
#define GPF3CONPDN			(ELFIN_GPIO_BASE + GPF3CONPDN_OFFSET)	 
#define GPF3PUDPDN			(ELFIN_GPIO_BASE + GPF3PUDPDN_OFFSET)	 
#define GPG0CON				(ELFIN_GPIO_BASE + GPG0CON_OFFSET) 
#define GPG0DAT				(ELFIN_GPIO_BASE + GPG0DAT_OFFSET)		 
#define GPG0PUD				(ELFIN_GPIO_BASE + GPG0PUD_OFFSET)		 
#define GPG0DRV				(ELFIN_GPIO_BASE + GPG0DRV_SR_OFFSET)
#define GPG0CONPDN			(ELFIN_GPIO_BASE + GPG0CONPDN_OFFSET)	 
#define GPG0PUDPDN			(ELFIN_GPIO_BASE + GPG0PUDPDN_OFFSET)	 
#define GPG1CON				(ELFIN_GPIO_BASE + GPG1CON_OFFSET) 
#define GPG1DAT				(ELFIN_GPIO_BASE + GPG1DAT_OFFSET)		 
#define GPG1PUD				(ELFIN_GPIO_BASE + GPG1PUD_OFFSET)		 
#define GPG1DRV				(ELFIN_GPIO_BASE + GPG1DRV_SR_OFFSET)
#define GPG1CONPDN			(ELFIN_GPIO_BASE + GPG1CONPDN_OFFSET)	 
#define GPG1PUDPDN			(ELFIN_GPIO_BASE + GPG1PUDPDN_OFFSET)	 
#define GPG2CON				(ELFIN_GPIO_BASE + GPG2CON_OFFSET) 
#define GPG2DAT				(ELFIN_GPIO_BASE + GPG2DAT_OFFSET)		 
#define GPG2PUD				(ELFIN_GPIO_BASE + GPG2PUD_OFFSET)		 
#define GPG2DRV				(ELFIN_GPIO_BASE + GPG2DRV_SR_OFFSET)
#define GPG2CONPDN			(ELFIN_GPIO_BASE + GPG2CONPDN_OFFSET)	 
#define GPG2PUDPDN			(ELFIN_GPIO_BASE + GPG2PUDPDN_OFFSET)	 
#define GPG3CON				(ELFIN_GPIO_BASE + GPG3CON_OFFSET) 
#define GPG3DAT				(ELFIN_GPIO_BASE + GPG3DAT_OFFSET)		 
#define GPG3PUD				(ELFIN_GPIO_BASE + GPG3PUD_OFFSET)		 
#define GPG3DRV				(ELFIN_GPIO_BASE + GPG3DRV_SR_OFFSET)
#define GPG3CONPDN			(ELFIN_GPIO_BASE + GPG3CONPDN_OFFSET)	 
#define GPG3PUDPDN			(ELFIN_GPIO_BASE + GPG3PUDPDN_OFFSET)
#define GPH0CON				(ELFIN_GPIO_BASE + GPH0CON_OFFSET)
#define GPH0DAT				(ELFIN_GPIO_BASE + GPH0DAT_OFFSET)
#define GPH0PUD				(ELFIN_GPIO_BASE + GPH0PUD_OFFSET)
#define GPH0DRV				(ELFIN_GPIO_BASE + GPH0DRV_OFFSET)
#define GPH1CON				(ELFIN_GPIO_BASE + GPH1CON_OFFSET)
#define GPH1DAT				(ELFIN_GPIO_BASE + GPH1DAT_OFFSET)
#define GPH1PUD				(ELFIN_GPIO_BASE + GPH1PUD_OFFSET)
#define GPH1DRV				(ELFIN_GPIO_BASE + GPH1DRV_OFFSET)
#define GPH2CON				(ELFIN_GPIO_BASE + GPH2CON_OFFSET)
#define GPH2DAT				(ELFIN_GPIO_BASE + GPH2DAT_OFFSET)
#define GPH2PUD				(ELFIN_GPIO_BASE + GPH2PUD_OFFSET)
#define GPH2DRV				(ELFIN_GPIO_BASE + GPH2DRV_OFFSET)
#define GPICON				(ELFIN_GPIO_BASE + GPICON_OFFSET) 
#define GPIPUD				(ELFIN_GPIO_BASE + GPIPUD_OFFSET)			 
#define GPIDRV				(ELFIN_GPIO_BASE + GPIDRV_OFFSET_SR)
#define GPIPUDPDN			(ELFIN_GPIO_BASE + GPIPUDPDN_OFFSET)	 
#define GPJ0CON				(ELFIN_GPIO_BASE + GPJ0CON_OFFSET)	 
#define GPJ0DAT				(ELFIN_GPIO_BASE + GPJ0DAT_OFFSET)		 
#define GPJ0PUD				(ELFIN_GPIO_BASE + GPJ0PUD_OFFSET)		 
#define GPJ0DRV				(ELFIN_GPIO_BASE + GPJ0DRV_SR_OFFSET)
#define GPJ0CONPDN			(ELFIN_GPIO_BASE + GPJ0CONPDN_OFFSET)	 
#define GPJ0PUDPDN			(ELFIN_GPIO_BASE + GPJ0PUDPDN_OFFSET)	 
#define GPJ1CON				(ELFIN_GPIO_BASE + GPJ1CON_OFFSET) 
#define GPJ1DAT				(ELFIN_GPIO_BASE + GPJ1DAT_OFFSET)		 
#define GPJ1PUD				(ELFIN_GPIO_BASE + GPJ1PUD_OFFSET)		 
#define GPJ1DRV				(ELFIN_GPIO_BASE + GPJ1DRV_SR_OFFSET)
#define GPJ1CONPDN			(ELFIN_GPIO_BASE + GPJ1CONPDN_OFFSET)	 
#define GPJ1PUDPDN			(ELFIN_GPIO_BASE + GPJ1PUDPDN_OFFSET)	 
#define GPJ2CON				(ELFIN_GPIO_BASE + GPJ2CON_OFFSET) 
#define GPJ2DAT				(ELFIN_GPIO_BASE + GPJ2DAT_OFFSET)		 
#define GPJ2PUD				(ELFIN_GPIO_BASE + GPJ2PUD_OFFSET)		 
#define GPJ2DRV				(ELFIN_GPIO_BASE + GPJ2DRV_SR_OFFSET)
#define GPJ2CONPDN			(ELFIN_GPIO_BASE + GPJ2CONPDN_OFFSET)	 
#define GPJ2PUDPDN			(ELFIN_GPIO_BASE + GPJ2PUDPDN_OFFSET)	 
#define GPJ3CON				(ELFIN_GPIO_BASE + GPJ3CON_OFFSET) 
#define GPJ3DAT				(ELFIN_GPIO_BASE + GPJ3DAT_OFFSET)		 
#define GPJ3PUD				(ELFIN_GPIO_BASE + GPJ3PUD_OFFSET)		 
#define GPJ3DRV_SR			(ELFIN_GPIO_BASE + GPJ3DRV_SR_OFFSET)
#define GPJ3CONPDN			(ELFIN_GPIO_BASE + GPJ3CONPDN_OFFSET)	 
#define GPJ3PUDPDN			(ELFIN_GPIO_BASE + GPJ3PUDPDN_OFFSET)	 
#define GPJ4CON				(ELFIN_GPIO_BASE + GPJ4CON_OFFSET)
#define GPJ4DAT				(ELFIN_GPIO_BASE + GPJ4DAT_OFFSET)		 
#define GPJ4PUD				(ELFIN_GPIO_BASE + GPJ4PUD_OFFSET)		 
#define GPJ4DRV				(ELFIN_GPIO_BASE + GPJ4DRV_SR_OFFSET)
#define GPJ4CONPDN			(ELFIN_GPIO_BASE + GPJ4CONPDN_OFFSET)	 
#define GPJ4PUDPDN			(ELFIN_GPIO_BASE + GPJ4PUDPDN_OFFSET)

#define MP1_0DRV_SR_OFFSET 		0x3CC
#define MP1_1DRV_SR_OFFSET 		0x3EC
#define MP1_2DRV_SR_OFFSET 		0x40C
#define MP1_3DRV_SR_OFFSET 		0x42C
#define MP1_4DRV_SR_OFFSET 		0x44C
#define MP1_5DRV_SR_OFFSET 		0x46C
#define MP1_6DRV_SR_OFFSET 		0x48C
#define MP1_7DRV_SR_OFFSET 		0x4AC
#define MP1_8DRV_SR_OFFSET 		0x4CC

#define MP2_0DRV_SR_OFFSET 		0x4EC
#define MP2_1DRV_SR_OFFSET 		0x50C
#define MP2_2DRV_SR_OFFSET 		0x52C
#define MP2_3DRV_SR_OFFSET 		0x54C
#define MP2_4DRV_SR_OFFSET 		0x56C
#define MP2_5DRV_SR_OFFSET 		0x58C
#define MP2_6DRV_SR_OFFSET 		0x5AC
#define MP2_7DRV_SR_OFFSET 		0x5CC
#define MP2_8DRV_SR_OFFSET 		0x5EC
/* - end of gpio controller reg config */

/* - clock controller reg config */
#define ELFIN_CLOCK_POWER_BASE		0xE0100000	

#define APLL_LOCK_OFFSET		0x00		
#define MPLL_LOCK_OFFSET		0x08

#define APLL_CON0_OFFSET		0x100
#define APLL_CON1_OFFSET		0x104
#define MPLL_CON_OFFSET			0x108

#define CLK_SRC0_OFFSET			0x200
#define CLK_SRC1_OFFSET			0x204
#define CLK_SRC2_OFFSET			0x208
#define CLK_SRC3_OFFSET			0x20c
#define CLK_SRC4_OFFSET			0x210
#define CLK_SRC5_OFFSET			0x214
#define CLK_SRC6_OFFSET			0x218
#define CLK_SRC_MASK0_OFFSET	0x280
#define CLK_SRC_MASK1_OFFSET	0x284

#define CLK_DIV0_OFFSET			0x300
#define CLK_DIV1_OFFSET			0x304
#define CLK_DIV2_OFFSET			0x308
#define CLK_DIV3_OFFSET			0x30c
#define CLK_DIV4_OFFSET			0x310
#define CLK_DIV5_OFFSET			0x314
#define CLK_DIV6_OFFSET			0x318
#define CLK_DIV7_OFFSET			0x31c

#define CLK_DIV0_MASK			0x7fffffff

#define APLL_LOCK_REG			__REG(ELFIN_CLOCK_POWER_BASE+APLL_LOCK_OFFSET)
#define MPLL_LOCK_REG			__REG(ELFIN_CLOCK_POWER_BASE+MPLL_LOCK_OFFSET
//#define EPLL_LOCK_REG			__REG(ELFIN_CLOCK_POWER_BASE+EPLL_LOCK_OFFSET)
//#define HPLL_LOCK_REG			__REG(ELFIN_CLOCK_POWER_BASE+HPLL_LOCK_OFFSET)
#define APLL_CON0_REG			__REG(ELFIN_CLOCK_POWER_BASE+APLL_CON0_OFFSET)
#define APLL_CON1_REG			__REG(ELFIN_CLOCK_POWER_BASE+APLL_CON1_OFFSET)
#define MPLL_CON_REG			__REG(ELFIN_CLOCK_POWER_BASE+MPLL_CON_OFFSET)
//#define EPLL_CON_REG			__REG(ELFIN_CLOCK_POWER_BASE+EPLL_CON_OFFSET)
//#define HPLL_CON_REG			__REG(ELFIN_CLOCK_POWER_BASE+HPLL_CON_OFFSET)
#define CLK_SRC0_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_SRC0_OFFSET)
#define CLK_SRC1_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_SRC1_OFFSET)
#define CLK_SRC2_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_SRC2_OFFSET)
#define CLK_SRC3_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_SRC3_OFFSET)
#define CLK_SRC4_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_SRC4_OFFSET)
#define CLK_DIV0_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV0_OFFSET)
#define CLK_DIV1_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV1_OFFSET)
#define CLK_DIV2_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV2_OFFSET)
#define CLK_DIV3_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV3_OFFSET)
#define CLK_DIV4_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV4_OFFSET)
#define CLK_DIV5_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV5_OFFSET)
#define CLK_DIV6_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV6_OFFSET)
#define CLK_DIV7_REG			__REG(ELFIN_CLOCK_POWER_BASE+CLK_DIV7_OFFSET)

/* - clock value config */
#define APLL_MDIV      	 		0x7d		// 125
#define APLL_PDIV       		0x3
#define APLL_SDIV       		0x1

#define MPLL_MDIV				0x29b		// 667
#define MPLL_PDIV				0xc
#define MPLL_SDIV				0x1

#define set_pll(mdiv, pdiv, sdiv)	(1<<31 | mdiv<<16 | pdiv<<8 | sdiv)
#define APLL_VAL			set_pll(APLL_MDIV,APLL_PDIV,APLL_SDIV)
#define MPLL_VAL			set_pll(MPLL_MDIV,MPLL_PDIV,MPLL_SDIV)
/* - end of clk controller reg config */

/* - sdram controller reg config */
#define APB_DMC_0_BASE			0xF0000000
#define APB_DMC_1_BASE			0xF1400000
#define ASYNC_MSYS_DMC0_BASE		0xF1E00000

#define DMC_CONCONTROL 			0x00
#define DMC_MEMCONTROL 			0x04
#define DMC_MEMCONFIG0 			0x08
#define DMC_MEMCONFIG1 			0x0C
#define DMC_DIRECTCMD 			0x10
#define DMC_PRECHCONFIG 		0x14
#define DMC_PHYCONTROL0 		0x18
#define DMC_PHYCONTROL1 		0x1C
#define DMC_RESERVED 			0x20
#define DMC_PWRDNCONFIG 		0x28
#define DMC_TIMINGAREF 			0x30
#define DMC_TIMINGROW 			0x34
#define DMC_TIMINGDATA 			0x38
#define DMC_TIMINGPOWER 		0x3C
#define DMC_PHYSTATUS 			0x40
#define DMC_CHIP0STATUS 		0x48
#define DMC_CHIP1STATUS 		0x4C
#define DMC_AREFSTATUS 			0x50
#define DMC_MRSTATUS 			0x54
#define DMC_PHYTEST0 			0x58
#define DMC_PHYTEST1 			0x5C
#define DMC_QOSCONTROL0 		0x60
#define DMC_QOSCONFIG0 			0x64
#define DMC_QOSCONTROL1 		0x68
#define DMC_QOSCONFIG1 			0x6C
#define DMC_QOSCONTROL2 		0x70
#define DMC_QOSCONFIG2 			0x74
#define DMC_QOSCONTROL3 		0x78
#define DMC_QOSCONFIG3 			0x7C
#define DMC_QOSCONTROL4 		0x80
#define DMC_QOSCONFIG4 			0x84
#define DMC_QOSCONTROL5 		0x88
#define DMC_QOSCONFIG5 			0x8C
#define DMC_QOSCONTROL6 		0x90
#define DMC_QOSCONFIG6 			0x94
#define DMC_QOSCONTROL7 		0x98
#define DMC_QOSCONFIG7 			0x9C
#define DMC_QOSCONTROL8 		0xA0
#define DMC_QOSCONFIG8 			0xA4
#define DMC_QOSCONTROL9 		0xA8
#define DMC_QOSCONFIG9 			0xAC
#define DMC_QOSCONTROL10 		0xB0
#define DMC_QOSCONFIG10 		0xB4
#define DMC_QOSCONTROL11 		0xB8
#define DMC_QOSCONFIG11 		0xBC
#define DMC_QOSCONTROL12 		0xC0
#define DMC_QOSCONFIG12 		0xC4
#define DMC_QOSCONTROL13 		0xC8
#define DMC_QOSCONFIG13 		0xCC
#define DMC_QOSCONTROL14 		0xD0
#define DMC_QOSCONFIG14 		0xD4
#define DMC_QOSCONTROL15 		0xD8
#define DMC_QOSCONFIG15 		0xDC
/* - end of controller reg config */

/* - sd/mmc reg config */
#define ELFIN_HSMMC_0_BASE		0xEB000000
#define ELFIN_HSMMC_1_BASE		0xEB100000
#define ELFIN_HSMMC_2_BASE		0xEB200000
#define ELFIN_HSMMC_3_BASE		0xEB300000
/* - end of sd/mmc reg config */


#endif /* S5PC110_H_ */